import Link from "next/link"
import { ArrowRight, Check } from "lucide-react"
import { MarketingFooter, MarketingNav } from "@/components/marketing/site"
import { Button } from "@/components/ui/button"

export type VerticalKey = "agencies" | "consultants" | "msps" | "freelancers"

const VERTICALS: Record<VerticalKey, { eyebrow: string; title: string; intro: string; points: string[]; example: string }> = {
  agencies: { eyebrow: "For creative and marketing agencies", title: "Protect the client relationship while you recover the balance.", intro: "Keep project invoices moving without asking your team to become full-time debt chasers. Overdue gives every client a clear, human next step.", points: ["Import project invoices from a CSV", "Use a gentle-to-firm ladder per client", "Pause automatically when a client replies", "Keep promises and payment history visible"], example: "A $4,800 campaign invoice is late. The first message is a calm check-in; the final step sets a clear date without burning the relationship." },
  consultants: { eyebrow: "For consultants and advisors", title: "Spend your time advising clients, not reminding them to pay.", intro: "Your work is personal. Your follow-up can be systematic. Overdue keeps the wording in your voice while making the timing reliable.", points: ["Send a clear invoice-specific follow-up", "Let clients request a date or payment plan", "Review every draft before it carries your name", "See which promises need attention today"], example: "A retained advisory invoice slips past net-30. Overdue asks for a date, pauses when the client responds and puts the commitment on the timeline." },
  msps: { eyebrow: "For MSPs and IT service teams", title: "Make recurring invoice follow-up part of the service rhythm.", intro: "Recurring work deserves recurring discipline. Overdue keeps open balances visible while your team stays focused on uptime and delivery.", points: ["Group open invoices by customer", "Escalate only when silence continues", "Record disputes and promised dates", "Hand a clean recovery history to finance"], example: "A managed-services customer is 18 days late. The account owner sees the promise, next reminder and balance in one place." },
  freelancers: { eyebrow: "For freelancers and solo studios", title: "Ask for payment without making it a whole conversation.", intro: "A small business should not need a collections department. Import your overdue list, choose a ladder and keep the decision in your hands.", points: ["Start free with Smart CSV", "Edit every email before sending", "Stop the ladder when payment or a reply arrives", "Keep the ledger ready for tax and cash planning"], example: "A freelance developer has three late invoices. One CSV upload turns the list into three clear next actions instead of three awkward drafts." },
}

export function VerticalLanding({ kind }: { kind: VerticalKey }) {
  const content = VERTICALS[kind]
  return <div className="min-h-screen bg-paper"><MarketingNav /><main><section className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-20 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:pt-28"><div><div className="font-mono text-[11px] uppercase tracking-[0.16em] text-moss">{content.eyebrow}</div><h1 className="mt-4 font-display text-5xl leading-[1.02] tracking-tight text-ink sm:text-6xl">{content.title}</h1><p className="mt-6 max-w-measure text-lg leading-relaxed text-ink-soft">{content.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup"><Button size="lg">Start free</Button></Link><Link href="/#how"><Button size="lg" variant="outline">See how it works</Button></Link></div></div><div className="rounded-2xl border border-hairline bg-surface p-7 shadow-ledger"><div className="font-mono text-[10px] uppercase tracking-[0.14em] text-faint">A typical recovery moment</div><p className="mt-5 font-display text-2xl leading-tight text-ink">“{content.example}”</p><div className="mt-7 rounded-xl bg-paper p-4"><div className="font-mono text-[10px] uppercase tracking-[0.12em] text-moss">Overdue next action</div><div className="mt-2 flex items-center justify-between gap-3 text-sm text-ink-soft"><span>Review a human draft</span><ArrowRight className="h-4 w-4 text-moss" /></div></div></div></section><section className="border-y border-hairline bg-surface/65 py-16"><div className="mx-auto max-w-6xl px-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{content.points.map((point) => <div key={point} className="rounded-xl border border-hairline bg-surface p-5 shadow-ledger"><Check className="h-5 w-5 text-moss" /><p className="mt-4 text-sm leading-relaxed text-ink-soft">{point}</p></div>)}</div></div></section></main><MarketingFooter /></div>
}
